### ISSUE TITLE
An error about 'blockchain_key' when 'make run'

### ISSUE THREAD

**Issue by neichen** [rubykube/workbench#123]
Thanks for the excellent work.
I installed workbench according to the README.md and I got the following error when running "make run"

> System: CentOS7.4

Any ideas about it?
```
...

Migrating to AddMissingIndexForAuthentications (20180605104154)
== 20180605104154 AddMissingIndexForAuthentications: migrating ================
-- add_index(:authentications, [:provider, :member_id, :uid], {:unique=>true})
   -> 0.1241s
== 20180605104154 AddMissingIndexForAuthentications: migrated (0.1242s) =======

Model files unchanged.
rake aborted!
ActiveRecord::UnknownAttributeError: unknown attribute 'blockchain_key' for Currency.
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:59:in `rescue in _assign_attribute'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:53:in `_assign_attribute'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:41:in `block in assign_attributes'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:35:in `each'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:35:in `assign_attributes'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/core.rb:566:in `init_attributes'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/core.rb:281:in `initialize'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/inheritance.rb:61:in `new'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/inheritance.rb:61:in `new'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/persistence.rb:50:in `create!'
/home/app/lib/tasks/currencies.rake:11:in `block (4 levels) in <top (required)>'
/home/app/lib/tasks/currencies.rake:9:in `each'
/home/app/lib/tasks/currencies.rake:9:in `block (3 levels) in <top (required)>'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/transactions.rb:220:in `transaction'
/home/app/lib/tasks/currencies.rake:8:in `block (2 levels) in <top (required)>'
/home/app/db/seeds.rb:4:in `<top (required)>'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `block in load'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:547:in `load_seed'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:253:in `load_seed'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/railties/databases.rake:173:in `block (2 levels) in <top (required)>'
/opt/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'

Caused by:
NoMethodError: undefined method `blockchain_key=' for #<Currency:0x000055873bbf73c8>
/opt/vendor/bundle/ruby/2.5.0/gems/activemodel-4.2.10/lib/active_model/attribute_methods.rb:433:in `method_missing'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:54:in `public_send'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:54:in `_assign_attribute'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:41:in `block in assign_attributes'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:35:in `each'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:35:in `assign_attributes'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/core.rb:566:in `init_attributes'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/core.rb:281:in `initialize'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/inheritance.rb:61:in `new'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/inheritance.rb:61:in `new'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/persistence.rb:50:in `create!'
/home/app/lib/tasks/currencies.rake:11:in `block (4 levels) in <top (required)>'
/home/app/lib/tasks/currencies.rake:9:in `each'
/home/app/lib/tasks/currencies.rake:9:in `block (3 levels) in <top (required)>'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/transactions.rb:220:in `transaction'
/home/app/lib/tasks/currencies.rake:8:in `block (2 levels) in <top (required)>'
/home/app/db/seeds.rb:4:in `<top (required)>'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `block in load'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:547:in `load_seed'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:253:in `load_seed'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/railties/databases.rake:173:in `block (2 levels) in <top (required)>'
/opt/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => currencies:seed
(See full trace by running task with --trace)
make: *** [setup-apps] Error 1
```

**Comment by almantasr** [comment]
Update peatio submodule, check on what branch you are. change to master branch it should be ok

**Comment by laugh26** [comment]
I checked all master branch but still got the error 
[submodule "peatio"]
        path = app/peatio
        url = https://github.com/rubykube/peatio.git
        branch = "master"
[submodule "barong"]
        path = app/barong
        url = https://github.com/rubykube/barong.git
        branch = "master"
[submodule "trading-ui"]
        path = app/trading-ui
        url = https://github.com/rubykube/peatio-trading-ui.git
        branch = "master"
[submodule "toolbox"]
        path = app/toolbox
        url = https://github.com/rubykube/toolbox.git
        branch = "master"
