### ISSUE TITLE
`make run` failed

### ISSUE THREAD

**Issue by chptx** [rubykube/workbench#144]
platform: ubuntu 16.04
docker: 18.06.1-ce
docker compose: 1.22.0

workbench from master branch, follow the README steps and `make run` failed:

```bash
make build
make bitcoin
make run

... ...

   (0.1ms)  SHOW CREATE TABLE `orders`
Model files unchanged.
  ActiveRecord::SchemaMigration Load (0.7ms)  SELECT `schema_migrations`.* FROM `schema_migrations`
   (0.2ms)  BEGIN
  Currency Exists (58.0ms)  SELECT  1 AS one FROM `currencies` WHERE `currencies`.`id` = 'usd' LIMIT 1
  Currency Exists (139.8ms)  SELECT  1 AS one FROM `currencies` WHERE `currencies`.`id` = BINARY 'usd' LIMIT 1
  SQL (0.3ms)  INSERT INTO `currencies` (`options`, `id`, `symbol`, `type`, `quick_withdraw_limit`, `created_at`, `updated_at`) VALUES ('{\"bitgo_wallet_address\":null,\"erc20_contract_address\":null}', 'usd', '$', 'fiat', 1000.0, '2018-08-30 06:41:57', '2018-08-30 06:41:57')
  Member Load (0.2ms)  SELECT  `members`.* FROM `members`  ORDER BY `members`.`id` ASC LIMIT 1000
  Currency Exists (0.2ms)  SELECT  1 AS one FROM `currencies` WHERE `currencies`.`id` = 'eth' LIMIT 1
   (58.8ms)  ROLLBACK
rake aborted!
ActiveRecord::UnknownAttributeError: unknown attribute 'blockchain_key' for Currency.
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:59:in `rescue in _assign_attribute'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:53:in `_assign_attribute'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:41:in `block in assign_attributes'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:35:in `each'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:35:in `assign_attributes'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/core.rb:566:in `init_attributes'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/core.rb:281:in `initialize'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/inheritance.rb:61:in `new'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/inheritance.rb:61:in `new'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/persistence.rb:50:in `create!'
/home/app/lib/tasks/currencies.rake:11:in `block (4 levels) in <top (required)>'
/home/app/lib/tasks/currencies.rake:9:in `each'
/home/app/lib/tasks/currencies.rake:9:in `block (3 levels) in <top (required)>'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/transactions.rb:220:in `transaction'
/home/app/lib/tasks/currencies.rake:8:in `block (2 levels) in <top (required)>'
/home/app/db/seeds.rb:4:in `<top (required)>'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `block in load'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:547:in `load_seed'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:253:in `load_seed'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/railties/databases.rake:173:in `block (2 levels) in <top (required)>'
/opt/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/usr/local/bundle/bin/bundle:104:in `load'
/usr/local/bundle/bin/bundle:104:in `<main>'

Caused by:
NoMethodError: undefined method `blockchain_key=' for #<Currency:0x0000562de29fb670>
/opt/vendor/bundle/ruby/2.5.0/gems/activemodel-4.2.10/lib/active_model/attribute_methods.rb:433:in `method_missing'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:54:in `public_send'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:54:in `_assign_attribute'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:41:in `block in assign_attributes'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:35:in `each'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:35:in `assign_attributes'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/core.rb:566:in `init_attributes'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/core.rb:281:in `initialize'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/inheritance.rb:61:in `new'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/inheritance.rb:61:in `new'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/persistence.rb:50:in `create!'
/home/app/lib/tasks/currencies.rake:11:in `block (4 levels) in <top (required)>'
/home/app/lib/tasks/currencies.rake:9:in `each'
/home/app/lib/tasks/currencies.rake:9:in `block (3 levels) in <top (required)>'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/transactions.rb:220:in `transaction'
/home/app/lib/tasks/currencies.rake:8:in `block (2 levels) in <top (required)>'
/home/app/db/seeds.rb:4:in `<top (required)>'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `block in load'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:547:in `load_seed'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:253:in `load_seed'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/railties/databases.rake:173:in `block (2 levels) in <top (required)>'
/opt/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/usr/local/bundle/bin/bundle:104:in `load'
/usr/local/bundle/bin/bundle:104:in `<main>'
Tasks: TOP => currencies:seed
(See full trace by running task with --trace)
Makefile:42: recipe for target 'setup-apps' failed
make: *** [setup-apps] Error 1
```

**Comment by shal** [comment]
Hello @chptx,

Please try the following:

Cleanup app directory

```sh
$> rm -rf app/*
```

Udpdate submodules

```sh
$> make update
```

**Comment by knkrth** [comment]
I also have the same error. Removing `rm -rf app/*`  & `make update` doesn't solve the problem. 

```
/usr/local/bundle/bin/bundle:104:in `load'
/usr/local/bundle/bin/bundle:104:in `<main>'
Tasks: TOP => currencies:seed
(See full trace by running task with --trace)
Makefile:60: recipe for target 'setup-apps' failed
make: *** [setup-apps] Error 1
```

**Comment by MerlinMagic2018** [comment]
Following this video tutorial : https://www.youtube.com/watch?v=8bX3d6Za5g8

Debian
Google Cloud Instance

make run fails....

Here :



Blockchain Exists (0.6ms)  SELECT  1 AS one FROM `blockchains` WHERE `blockcha                                                  ins`.`key` = 'eth-rinkeby' LIMIT 1
  SQL (0.5ms)  INSERT INTO `blockchains` (`key`, `name`, `client`, `server`, `he                                                  ight`, `status`, `explorer_address`, `explorer_transaction`, `created_at`, `upda                                                  ted_at`) VALUES ('eth-rinkeby', 'Ethereum Rinkeby', 'ethereum', 'http://geth:854                                                  5', 2756436, 'active', 'https://rinkeby.etherscan.io/address/#{address}', 'https                                                  ://rinkeby.etherscan.io/tx/#{txid}', '2018-11-29 01:05:53', '2018-11-29 01:05:53                                                  ')
   (3.7ms)  COMMIT
   (0.3ms)  BEGIN
  Currency Exists (0.5ms)  SELECT  1 AS one FROM `currencies` WHERE `currencies`                                                  .`id` = 'usd' LIMIT 1
   (0.3ms)  ROLLBACK
rake aborted!
ActiveRecord::UnknownAttributeError: unknown attribute 'quick_withdraw_limit' fo                                                  r Currency.

**Comment by MerlinMagic2018** [comment]
Tasks: TOP => seed:currencies
(See full trace by running task with --trace)
Makefile:64: recipe for target 'setup-apps' failed
make: *** [setup-apps] Error 1

**Comment by MerlinMagic2018** [comment]
so I did the 

rm -rf app/*

make update

And then reran 

make run

Surprise, the same error.

ActiveRecord::UnknownAttributeError: unknown attribute 'quick_withdraw_limit' for Currency.

**Comment by AkashiHidaka** [comment]
Again occur this error.
It isn't solve.

**Comment by sp1k31973** [comment]
same issue here

**Comment by denstepa** [comment]
We had same problem, and this helped to fix it (https://github.com/rubykube/peatio/pull/1904) however i am not sure if its correct to use seeds from this repository and not from workbench
