### ISSUE TITLE
make stress error - undefined method `transform_keys' 

### ISSUE THREAD

**Issue by daemonico** [rubykube/workbench#193]
"make stress" command not working due to undefined method.

## installation info
```
/workbench - master
/app/peatio - 1-9-stable
/app/trading-ui - 1.9.1-rc.9
```

## error message
```
/workbench$ make stress
rake aborted!
NoMethodError: undefined method `transform_keys' for #<Hash:0x00000002beed10>
lib/tasks/toolbox.rake:11:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/var/lib/gems/2.3.0/gems/bundler-1.16.5/lib/bundler/cli/exec.rb:74:in `load'
/var/lib/gems/2.3.0/gems/bundler-1.16.5/lib/bundler/cli/exec.rb:74:in `kernel_load'
/var/lib/gems/2.3.0/gems/bundler-1.16.5/lib/bundler/cli/exec.rb:28:in `run'
/var/lib/gems/2.3.0/gems/bundler-1.16.5/lib/bundler/cli.rb:424:in `exec'
/var/lib/gems/2.3.0/gems/bundler-1.16.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/lib/gems/2.3.0/gems/bundler-1.16.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/var/lib/gems/2.3.0/gems/bundler-1.16.5/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/var/lib/gems/2.3.0/gems/bundler-1.16.5/lib/bundler/cli.rb:27:in `dispatch'
/var/lib/gems/2.3.0/gems/bundler-1.16.5/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/var/lib/gems/2.3.0/gems/bundler-1.16.5/lib/bundler/cli.rb:18:in `start'
/var/lib/gems/2.3.0/gems/bundler-1.16.5/exe/bundle:30:in `block in <top (required)>'
/var/lib/gems/2.3.0/gems/bundler-1.16.5/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/var/lib/gems/2.3.0/gems/bundler-1.16.5/exe/bundle:22:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => toolbox:run
(See full trace by running task with --trace)
Makefile:71: recipe for target 'stress' failed
make: *** [stress] Error 1
```

**Comment by daemonico** [comment]
Hi @shal , upgrading the ruby works. Thanks you.
