### ISSUE TITLE
Initial setup problem on macOS

### ISSUE THREAD

**Issue by vincent-syncodax** [rubykube/workbench#201]
I am currently running the instructions as said in the README on macOS Mojave.

The problem is, during **make run**, I get the following error message:

```
Couldn't create database for {"adapter"=>"mysql2", "encoding"=>"utf8", "collation"=>"utf8_general_ci", "pool"=>5, "host"=>"db", "port"=>3306, "username"=>"root", "password"=>"changeme", "database"=>"peatio_development"}, {:charset=>"utf8", :collation=>"utf8_general_ci"}
(If you set the charset manually, make sure you have a matching collation)
rake aborted!
Mysql2::Error: Unknown MySQL server host 'db' (-2)
/opt/vendor/bundle/ruby/2.5.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:89:in `connect'
/opt/vendor/bundle/ruby/2.5.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:89:in `initialize'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `new'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `mysql2_connection'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_handling.rb:87:in `connection'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:941:in `initialize'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:823:in `new'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:823:in `up'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/migration.rb:801:in `migrate'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:139:in `migrate'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/opt/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
make: *** [setup-apps] Error 1
```

I was assuming that after running everything in the workbench install guide, everything will be fine. Please help.

**Comment by seletskiy** [comment]
@vincent-syncodax: it seems that you have problems with docker, because workbench expects to have `db` container up and running. Check your `docker ps`, if list doesn't contain `db` container, then it's not running. If it is contain `db`, then it's docker problem with names resolution in your system.

**Comment by vincent-syncodax** [comment]
I have tried deleting all the images and containers in my dev environment and was following the installation guide on a macOS environment.

During the process, I noticed that the mysql docker container exits unexpectedly.

Is the workbench environment supposed to run without problems just by following the installation guide?

**Comment by shal** [comment]
Hello @vincent-syncoda,

Unfortunately, there is a known issue with MacOS installation, because workbench have a lot of different resources, including `geth`.  Docker for mac is not such optimized, as on linux.

I suggest to comment few third-party dependencies in makefile, such as `geth`, `phpmyadmin`, but I would really recommend to run workbench on linux 😸

**Comment by vincent-syncodax** [comment]
Hello, I found out that I needed to add more memory to Docker default of 2 GB. I changed it to 4 GB but ws.ranger.wb.local shows "BAD GATEWAY" when I access it from a browser.
