### ISSUE TITLE
Gem::LoadError: You have already activated rake 12.3.0, but your Gemfile requires rake 12.3.1

### ISSUE THREAD

**Issue by ethermite** [rubykube/workbench#225]
Hello,

On following the install instruction when running the `docker-compose run --rm peatio bash -c "./bin/link_config && rake db:create db:migrate db:seed"` command getting.

```
Starting workbench_redis_1 ... done
Starting workbench_db_1    ... done
Starting workbench_proxy_1 ... done
Starting workbench_vault_1 ... done
Starting workbench_coinhub_1 ... done
Starting workbench_mailcatcher_1 ... done
Starting workbench_rabbitmq_1    ... done
Starting workbench_barong_1      ... done
Starting workbench_ranger_1      ... done
Link /opt/peatio/config/plugins.yml -> /home/app/config/plugins.yml
Link /opt/peatio/config/seed/wallets.yml -> /home/app/config/seed/wallets.yml
Link /opt/peatio/config/seed/currencies.yml -> /home/app/config/seed/currencies.yml
Link /opt/peatio/config/seed/blockchains.yml -> /home/app/config/seed/blockchains.yml
Link /opt/peatio/config/seed/markets.yml -> /home/app/config/seed/markets.yml
Link /opt/peatio/config/management_api_v1.yml -> /home/app/config/management_api_v1.yml
rake aborted!
Gem::LoadError: You have already activated rake 12.3.0, but your Gemfile requires rake 12.3.1. Prepending `bundle exec` to your command may solve this.
/home/app/config/boot.rb:6:in `<top (required)>'
/home/app/config/application.rb:4:in `<top (required)>'
/home/app/Rakefile:8:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by shal** [comment]
Hello @ethermite,

Command is invalid, because you need to use bundle inside peatio docker image.

```sh
$> docker-compose run --rm peatio bash -c "./bin/link_config && bundle exec rake db:create db:migrate db:seed"
```
