### ISSUE TITLE
make run error

### ISSUE THREAD

**Issue by jieek** [rubykube/workbench#245]
ActiveRecord::UnknownAttributeError: unknown attribute 'quick_withdraw_limit' for Currency.
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:59:in `rescue in _assign_attribute'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:53:in `_assign_attribute'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:41:in `block in assign_attributes'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:35:in `each'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/attribute_assignment.rb:35:in `assign_attributes'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/core.rb:566:in `init_attributes'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/core.rb:281:in `initialize'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/inheritance.rb:61:in `new'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/inheritance.rb:61:in `new'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/persistence.rb:50:in `create!'
/home/app/lib/tasks/seed.rake:11:in `block (4 levels) in <top (required)>'
/home/app/lib/tasks/seed.rake:9:in `each'
/home/app/lib/tasks/seed.rake:9:in `block (3 levels) in <top (required)>'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statem

**Comment by TTcoinDeveloper** [comment]
you need version 2.5.1, I think you should remove older version 2.5.0

**Comment by jieek** [comment]
my bundler info.
bobodeMacBook-Pro:workbench mac$ bundle
Using rake 12.3.1
Using bundler 1.17.1
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

**Comment by TTcoinDeveloper** [comment]
https://gorails.com/setup/ubuntu/16.04

**Comment by AkashiHidaka** [comment]
I have same error and it isn't work.
I installed all ruby and rails versions and need configs.
But I have same error and no compile the code.

Caused by:
NoMethodError: undefined method `quick_withdraw_limit=' for #<Currency:0x0000561                                                                                                                                                             2ca7c78f0>
/opt/vendor/bundle/ruby/2.5.0/gems/activemodel-4.2.10/lib/active_model/attribute                                                                                                                                                             _methods.rb:433:in `method_missing'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/attribu                                                                                                                                                             te_assignment.rb:54:in `public_send'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/attribu                                                                                                                                                             te_assignment.rb:54:in `_assign_attribute'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/attribu                                                                                                                                                             te_assignment.rb:41:in `block in assign_attributes'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/attribu                                                                                                                                                             te_assignment.rb:35:in `each'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/attribu                                                                                                                                                             te_assignment.rb:35:in `assign_attributes'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/core.rb                                                                                                                                                             :566:in `init_attributes'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/core.rb                                                                                                                                                             :281:in `initialize'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/inherit                                                                                                                                                             ance.rb:61:in `new'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/inherit                                                                                                                                                             ance.rb:61:in `new'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/persist                                                                                                                                                             ence.rb:50:in `create!'
/home/app/lib/tasks/seed.rake:11:in `block (4 levels) in <top (required)>'
/home/app/lib/tasks/seed.rake:9:in `each'
/home/app/lib/tasks/seed.rake:9:in `block (3 levels) in <top (required)>'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connect                                                                                                                                                             ion_adapters/abstract/database_statements.rb:213:in `block in transaction'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connect                                                                                                                                                             ion_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/connect                                                                                                                                                             ion_adapters/abstract/database_statements.rb:213:in `transaction'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/transac                                                                                                                                                             tions.rb:220:in `transaction'
/home/app/lib/tasks/seed.rake:8:in `block (2 levels) in <top (required)>'
/home/app/db/seeds.rb:6:in `<top (required)>'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/depen                                                                                                                                                             dencies.rb:268:in `load'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/depen                                                                                                                                                             dencies.rb:268:in `block in load'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/depen                                                                                                                                                             dencies.rb:240:in `load_dependency'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.10/lib/active_support/depen                                                                                                                                                             dencies.rb:268:in `load'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/engine.rb:547:in `l                                                                                                                                                             oad_seed'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/tasks/d                                                                                                                                                             atabase_tasks.rb:253:in `load_seed'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/railtie                                                                                                                                                             s/databases.rake:173:in `block (2 levels) in <top (required)>'
/opt/vendor/bundle/ruby/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => seed:currencies
(See full trace by running task with --trace)
Makefile:64: recipe for target 'setup-apps' failed
make: *** [setup-apps] Error 1
![image](https://user-images.githubusercontent.com/44053447/49476583-61b59980-f855-11e8-9445-0ee727be85e0.png)

**Comment by dragon28** [comment]
I am getting the same error as well

**Comment by Tunnulincadmin** [comment]
same here ... I have reinstall Ruby/Rails/Bundler  ... rebuilt again ... Same error >> have installed this successfully many times, never had this issue before

**Comment by AkashiHidaka** [comment]
Yes , I have backup code of 1.9 version and tested it.
But both old version and new version have same error .
It isn't work.

**Comment by gsilvestri** [comment]
I remember not having this problem with peatio 1.9

**Comment by AkashiHidaka** [comment]
But in 1.9 version no compile and show same error.

**Comment by AkashiHidaka** [comment]
I find the reason of the issues and if need help of it , touch me.

**Comment by gsilvestri** [comment]
can you share the reason-solution of the error for future reference please??

**Comment by TTcoinDeveloper** [comment]
Possible some sort of rollback bundler version might do it also try updating docker-compose to latest version

**Comment by AkashiHidaka** [comment]
Yes , TTcoinDeveloper word is same and if you know the reason , why now it is publish.
Main problem occur barong Mysql2 no connect error and it can update last docker version install and used Ubuntu 16.04 system.
Because some reason Debian system no installed "libmysqlclient-dev" and no connect mysql server.
![image](https://user-images.githubusercontent.com/44053447/49650567-926d1d00-fa67-11e8-96c3-47586e8e3160.png)
So follow this step.
1. Ubuntu 16.04 system use.
2. Last docker version install.
3. Mysql connect check.

**Comment by TTcoinDeveloper** [comment]
This is accurate I successfully built it on Ubuntu 16.04 before I rollback to Ubuntu 14.04 where the error was as above so yes I think minimal system requirements should be Ubuntu 16.04 and above
"libmysqlclient-dev" was not been able to install to  Ubuntu 14.04 as I also tried

**Comment by MerlinMagic2018** [comment]
edited the following lines in MakeFile :

setup-apps: build
	$(COMPOSE) run --rm peatio bash -c "./bin/link_config && bundle exec rake db:create db:migrate"
	$(COMPOSE) run --rm peatio bash -c "bundle exec rake seed:blockchains"
	$(COMPOSE) run --rm peatio bash -c "bundle exec rake seed:currencies"
	$(COMPOSE) run --rm peatio bash -c "bundle exec rake seed:wallets"
	$(COMPOSE) run --rm peatio bash -c "bundle exec rake seed:markets"
	$(COMPOSE) run --rm barong bash -c "./bin/link_config && ./bin/setup"

**Comment by MerlinMagic2018** [comment]
now it worked but if you get the next error ... ( barong mysql2 connection error when creating database )

Then try this : 
              password: <%= ENV.fetch('DATABASE_PASS', '**changeme**') %>
in the file : workbench/app/barong/config/database.yml

**Comment by shal** [comment]
Guys, this issue should be fixed in #265, I will close it after 10 days of inactivity.

**Comment by TTcoinDeveloper** [comment]
> edited the following lines in MakeFile :
> 
> setup-apps: build
> $(COMPOSE) run --rm peatio bash -c "./bin/link_config && bundle exec rake db:create db:migrate"
> $(COMPOSE) run --rm peatio bash -c "bundle exec rake seed:blockchains"
> $(COMPOSE) run --rm peatio bash -c "bundle exec rake seed:currencies"
> $(COMPOSE) run --rm peatio bash -c "bundle exec rake seed:wallets"
> $(COMPOSE) run --rm peatio bash -c "bundle exec rake seed:markets"
> $(COMPOSE) run --rm barong bash -c "./bin/link_config && ./bin/setup"



> now it worked but if you get the next error ... ( barong mysql2 connection error when creating database )
> 
> Then try this :
> password: <%= ENV.fetch('DATABASE_PASS', '**changeme**') %>
> in the file : workbench/app/barong/config/database.yml

@MerlinMagic2018 

I have suceeded with make build on workbench after trying for the longest while to make run but i keep getting mysql errors can u help me out bcuz i refuse to give up the workbench
