### ISSUE TITLE
Make Run Error. 

### ISSUE THREAD

**Issue by dudetheman** [rubykube/workbench#250]
Makefile:64: recipe for target 'setup-apps' failed
make: *** [setup-apps] Error 1

Getting 404 when I go to the website

**Comment by hashfaster** [comment]
Dev should be aware as circleci also has the same error on its CI activities..

https://circleci.com/gh/rubykube/workbench/266

**Comment by habrauser** [comment]
I'm also get the same error

**Comment by nithronium** [comment]
I have also tried deploying it today and got the same error.

My system is Ubuntu 18.04, 8GB RAM, 160 GB SSD

**Comment by nithronium** [comment]
Okay the error is being resolved if you delete the lines I showed on pull request. Remove "quick_withdraw_limit" parameters from config/peatio/seed/currencies.yml and config/peatio-seed-btc/currencies.yml

Detailed info is here : https://github.com/rubykube/workbench/pull/257/files

**Comment by nithronium** [comment]
However, there will be other problems after you fix this one. So I think it's better if the devs adjust everything properly.

**Comment by UfukAntep** [comment]
Make sure you're using successful commit. There are error in last commits. I'm using this commit (658c806056802ea12cb97522219db69af4a02fcf)

**Comment by gsilvestri** [comment]
Solved with the advice from @nithronium, however now I have the following error:
```
Couldn't create database for {"adapter"=>"mysql2", "encoding"=>"utf8", "pool"=>5, "host"=>"db", "port"=>3306, "username"=>"root", "password"=>nil, "database"=>"barong_development"}
rails aborted!
Mysql2::Error::ConnectionError: Access denied for user 'root'@'172.29.0.10' (using password: NO)
/home/app/vendor/bundle/ruby/2.5.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:90:in `connect'
/```

**Comment by nithronium** [comment]
> Solved with the advice from @nithronium, however now I have the following error:
> 
> ```
> Couldn't create database for {"adapter"=>"mysql2", "encoding"=>"utf8", "pool"=>5, "host"=>"db", "port"=>3306, "username"=>"root", "password"=>nil, "database"=>"barong_development"}
> rails aborted!
> Mysql2::Error::ConnectionError: Access denied for user 'root'@'172.29.0.10' (using password: NO)
> /home/app/vendor/bundle/ruby/2.5.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:90:in `connect'
> /```
> ```

The last commits have a lot of problems as @UfukAntep stated above. You could delete everything and try using a successful commit to build workbench. The error you have posted here is caused by MySQL installation being not correct.

**Comment by MerlinMagic2018** [comment]
I edited the following line :

             password: <%= ENV.fetch('DATABASE_PASS', 'changeme') %>

in workbench/app/barong/config/database.yml

And " make run " completed.

**Comment by shal** [comment]
Guys, this issue should be fixed in #265, I will close it after 10 days of inactivity.

**Comment by gsilvestri** [comment]
_Perfect_.
