### ISSUE TITLE
make run eroor - seed currencies

### ISSUE THREAD

**Issue by blopezmontalvo** [rubykube/workbench#261]
Currency Exists (0.6ms)  SELECT  1 AS one FROM `currencies` WHERE `currencies`            .`id` = 'usd' LIMIT 1
   (0.4ms)  ROLLBACK
rake aborted!
ActiveRecord::UnknownAttributeError: unknown attribute 'quick_withdraw_limit' fo            r Currency.
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/attribu            te_assignment.rb:59:in `rescue in _assign_attribute'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/attribu            te_assignment.rb:53:in `_assign_attribute'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/attribu            te_assignment.rb:41:in `block in assign_attributes'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/attribu            te_assignment.rb:35:in `each'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/attribu            te_assignment.rb:35:in `assign_attributes'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/core.rb            :566:in `init_attributes'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/core.rb            :281:in `initialize'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/inherit            ance.rb:61:in `new'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/inherit            ance.rb:61:in `new'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/persist            ence.rb:50:in `create!'
/home/app/lib/tasks/seed.rake:11:in `block (4 levels) in <top (required)>'
/home/app/lib/tasks/seed.rake:9:in `each'
/home/app/lib/tasks/seed.rake:9:in `block (3 levels) in <top (required)>'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/connect            ion_adapters/abstract/database_statements.rb:213:in `block in transaction'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/connect            ion_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/connect            ion_adapters/abstract/database_statements.rb:213:in `transaction'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/transac            tions.rb:220:in `transaction'
/home/app/lib/tasks/seed.rake:8:in `block (2 levels) in <top (required)>'
/home/app/db/seeds.rb:6:in `<top (required)>'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11/lib/active_support/depen            dencies.rb:268:in `load'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11/lib/active_support/depen            dencies.rb:268:in `block in load'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11/lib/active_support/depen            dencies.rb:240:in `load_dependency'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11/lib/active_support/depen            dencies.rb:268:in `load'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/engine.rb:547:in `l            oad_seed'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/tasks/d            atabase_tasks.rb:253:in `load_seed'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/railtie            s/databases.rake:173:in `block (2 levels) in <top (required)>'
/opt/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'

Caused by:
NoMethodError: undefined method `quick_withdraw_limit=' for #<Currency:0x0000563            6a0054b50>
/opt/vendor/bundle/ruby/2.5.0/gems/activemodel-4.2.11/lib/active_model/attribute            _methods.rb:433:in `method_missing'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/attribu            te_assignment.rb:54:in `public_send'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/attribu            te_assignment.rb:54:in `_assign_attribute'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/attribu            te_assignment.rb:41:in `block in assign_attributes'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/attribu            te_assignment.rb:35:in `each'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/attribu            te_assignment.rb:35:in `assign_attributes'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/core.rb            :566:in `init_attributes'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/core.rb            :281:in `initialize'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/inherit            ance.rb:61:in `new'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/inherit            ance.rb:61:in `new'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/persist            ence.rb:50:in `create!'
/home/app/lib/tasks/seed.rake:11:in `block (4 levels) in <top (required)>'
/home/app/lib/tasks/seed.rake:9:in `each'
/home/app/lib/tasks/seed.rake:9:in `block (3 levels) in <top (required)>'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/connect            ion_adapters/abstract/database_statements.rb:213:in `block in transaction'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/connect            ion_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/connect            ion_adapters/abstract/database_statements.rb:213:in `transaction'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/transac            tions.rb:220:in `transaction'
/home/app/lib/tasks/seed.rake:8:in `block (2 levels) in <top (required)>'
/home/app/db/seeds.rb:6:in `<top (required)>'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11/lib/active_support/depen            dencies.rb:268:in `load'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11/lib/active_support/depen            dencies.rb:268:in `block in load'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11/lib/active_support/depen            dencies.rb:240:in `load_dependency'
/opt/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11/lib/active_support/depen            dencies.rb:268:in `load'
/opt/vendor/bundle/ruby/2.5.0/gems/railties-4.2.11/lib/rails/engine.rb:547:in `l            oad_seed'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/tasks/d            atabase_tasks.rb:253:in `load_seed'
/opt/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.11/lib/active_record/railtie            s/databases.rake:173:in `block (2 levels) in <top (required)>'
/opt/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => seed:currencies
(See full trace by running task with --trace)
Makefile:64: fallo en las instrucciones para el objetivo 'setup-apps'
make: *** [setup-apps] Error 1

**Friends, I need you to help me solve this problem.**

**Comment by MerlinMagic2018** [comment]
edit the following lines in MakeFile :

setup-apps: build
    $(COMPOSE) run --rm peatio bash -c "./bin/link_config && bundle exec rake db:create db:migrate"
    $(COMPOSE) run --rm peatio bash -c "bundle exec rake seed:blockchains"
    $(COMPOSE) run --rm peatio bash -c "bundle exec rake seed:currencies"
    $(COMPOSE) run --rm peatio bash -c "bundle exec rake seed:wallets"
    $(COMPOSE) run --rm peatio bash -c "bundle exec rake seed:markets"
    $(COMPOSE) run --rm barong bash -c "./bin/link_config && ./bin/setup"

**Comment by shal** [comment]
Guys, this issue should be fixed in #265, I will close it after 10 days of inactivity.
