### ISSUE TITLE
KeyError: key not found: "COOKIES_SECRET_KEY"

### ISSUE THREAD

**Issue by propercoil** [rubykube/workbench#4]
New build getting this error on `make run`:

```
rake aborted!
KeyError: key not found: "COOKIES_SECRET_KEY"
/home/app/config/initializers/cookies_secret_key.rb:1:in `fetch'
/home/app/config/initializers/cookies_secret_key.rb:1:in `<top (required)>'
/opt/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/opt/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `block in load'
/opt/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/opt/vendor/bundle/ruby/2.4.0/gems/railties-4.2.10/lib/rails/engine.rb:652:in `block in load_config_initializer'
/opt/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/notifications.rb:166:in `instrument'
/opt/vendor/bundle/ruby/2.4.0/gems/railties-4.2.10/lib/rails/engine.rb:651:in `load_config_initializer'
/opt/vendor/bundle/ruby/2.4.0/gems/railties-4.2.10/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/opt/vendor/bundle/ruby/2.4.0/gems/railties-4.2.10/lib/rails/engine.rb:615:in `each'
/opt/vendor/bundle/ruby/2.4.0/gems/railties-4.2.10/lib/rails/engine.rb:615:in `block in <class:Engine>'
/opt/vendor/bundle/ruby/2.4.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `instance_exec'
/opt/vendor/bundle/ruby/2.4.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `run'
/opt/vendor/bundle/ruby/2.4.0/gems/railties-4.2.10/lib/rails/initializable.rb:55:in `block in run_initializers'
/opt/vendor/bundle/ruby/2.4.0/gems/railties-4.2.10/lib/rails/initializable.rb:44:in `each'
/opt/vendor/bundle/ruby/2.4.0/gems/railties-4.2.10/lib/rails/initializable.rb:44:in `tsort_each_child'
/opt/vendor/bundle/ruby/2.4.0/gems/railties-4.2.10/lib/rails/initializable.rb:54:in `run_initializers'
/opt/vendor/bundle/ruby/2.4.0/gems/railties-4.2.10/lib/rails/application.rb:352:in `initialize!'
/opt/vendor/bundle/ruby/2.4.0/gems/railties-4.2.10/lib/rails/railtie.rb:194:in `public_send'
/opt/vendor/bundle/ruby/2.4.0/gems/railties-4.2.10/lib/rails/railtie.rb:194:in `method_missing'
/home/app/config/environment.rb:5:in `<top (required)>'
/opt/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
/opt/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
/opt/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
/opt/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
/opt/vendor/bundle/ruby/2.4.0/gems/railties-4.2.10/lib/rails/application.rb:328:in `require_environment!'
/opt/vendor/bundle/ruby/2.4.0/gems/railties-4.2.10/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/opt/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/usr/local/bundle/bin/bundle:104:in `load'
/usr/local/bundle/bin/bundle:104:in `<main>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
make: *** [run] Error 1
```

**Comment by dkkoval** [comment]
Looks outdated, closing.
